name: Dev Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_job:
    name: Building the APK
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned."

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - run: echo "Build Debug APK start"
      - name: Build Debug APK
        env:
          API_URL: ${{ secrets.API_URL }}
        run: ./gradlew assembleDebug -PAPI_URL=$API_URL
      - run: echo "Build Debug APK complete"

      - run: echo "Upload APK start"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
      - run: echo "Upload APK complete"